objects=\
Color.o\
edge_darkening_2.o\
edge_darkening.o\
Filtering.o\
FImage.o\
image_abstraction_filter.o\
lerpColor.o\
modify_color.o\
modify_color_hsl.o\
modify_color_hsv.o\
paper_texture.o\
pigment_dispersion.o\
PImage.o\
PVector.o\
Tensor.o\
thewatercolorist_main.o\
turbulent_flow.o
